from __future__ import annotations

import hashlib
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "multi_model_workflow" / "comparison_report.md"


FILES = [
    ("Codex", "Blind attempt", "generated_proofs/codex/agnostic_attempt_1.lean"),
    ("Codex", "Repaired attempt", "generated_proofs/codex/agnostic_attempt_2_repaired.lean"),
    ("Codex", "Simplified attempt", "generated_proofs/codex/simplified_attempt.lean"),
    ("Claude", "Blind attempt", "generated_proofs/claude/agnostic_attempt_1.lean"),
    ("Claude", "Repaired attempt", "generated_proofs/claude/agnostic_attempt_2_repaired.lean"),
    ("Claude", "Simplified attempt", "generated_proofs/claude/simplified_attempt.lean"),
]


@dataclass
class ComparisonRow:
    model: str
    stage: str
    path: str
    compiles: bool
    exit_code: int
    output: str
    lines: int
    sha_prefix: str
    uses_calc: bool
    uses_omega: bool
    uses_add_right: bool
    uses_assoc: bool
    calls_main_theorem: bool
    extracts_conjunction: bool


def lake_command() -> str:
    winget_lake = (
        Path(os.environ.get("LOCALAPPDATA", ""))
        / "Microsoft"
        / "WinGet"
        / "Packages"
        / "Lean.Lean_Microsoft.Winget.Source_8wekyb3d8bbwe"
        / "lean-4.29.1-windows"
        / "bin"
        / "lake.exe"
    )
    if winget_lake.exists():
        return str(winget_lake)
    return "lake"


def strip_comments(text: str) -> str:
    without_block_comments = re.sub(r"/-!?.*?-/", "", text, flags=re.DOTALL)
    lines = []
    for line in without_block_comments.splitlines():
        stripped = line.strip()
        if stripped.startswith("--"):
            continue
        lines.append(line)
    return "\n".join(lines)


def sha_prefix(path: Path) -> str:
    digest = hashlib.sha256(path.read_bytes()).hexdigest().upper()
    return digest[:12]


def verify_lean_file(lake: str, path: str) -> tuple[bool, int, str]:
    completed = subprocess.run(
        [lake, "env", "lean", path],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    output = completed.stdout.strip()
    return completed.returncode == 0, completed.returncode, output


def compare_file(lake: str, model: str, stage: str, rel_path: str) -> ComparisonRow:
    path = ROOT / rel_path
    text = path.read_text(encoding="utf-8")
    code = strip_comments(text)
    compiles, exit_code, output = verify_lean_file(lake, rel_path)

    return ComparisonRow(
        model=model,
        stage=stage,
        path=rel_path,
        compiles=compiles,
        exit_code=exit_code,
        output=output,
        lines=len(text.splitlines()),
        sha_prefix=sha_prefix(path),
        uses_calc="calc" in code,
        uses_omega="omega" in code,
        uses_add_right="Nat.add_le_add_right" in code,
        uses_assoc="Nat.add_assoc" in code,
        calls_main_theorem="agnostic_erm_deterministic P" in code,
        extracts_conjunction=(".left" in code or ".right" in code),
    )


def yes_no(value: bool) -> str:
    return "Yes" if value else "No"


def true_false(value: bool) -> str:
    return "True" if value else "False"


def build_report(rows: list[ComparisonRow]) -> str:
    report: list[str] = []
    report.append("# Generated Proof Comparison Report")
    report.append("")
    report.append("Generated by `multi_model_workflow/run_comparison.py`.")
    report.append("")
    report.append("## Verification Summary")
    report.append("")
    report.append("| Model | Stage | File | Compiles? | Exit | Lines | SHA256 prefix |")
    report.append("| --- | --- | --- | --- | --- | ---: | --- |")
    for row in rows:
        report.append(
            f"| {row.model} | {row.stage} | `{row.path}` | "
            f"{yes_no(row.compiles)} | {row.exit_code} | {row.lines} | `{row.sha_prefix}` |"
        )

    report.append("")
    report.append("## Structural Feature Comparison")
    report.append("")
    report.append(
        "| Model | Stage | calc | omega | add_right | assoc | "
        "calls main theorem | extracts conjunction |"
    )
    report.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for row in rows:
        report.append(
            f"| {row.model} | {row.stage} | {true_false(row.uses_calc)} | "
            f"{true_false(row.uses_omega)} | {true_false(row.uses_add_right)} | "
            f"{true_false(row.uses_assoc)} | {true_false(row.calls_main_theorem)} | "
            f"{true_false(row.extracts_conjunction)} |"
        )

    report.append("")
    report.append("## Failure Outputs")
    report.append("")
    for row in rows:
        if row.compiles:
            continue
        report.append(f"### {row.model} - {row.stage}")
        report.append("")
        report.append("```text")
        report.append(row.output if row.output else "(no output)")
        report.append("```")
        report.append("")

    report.append("## Interpretation")
    report.append("")
    report.append(
        "- Blind attempts are allowed to fail; their failures are the verifier feedback used for repair."
    )
    report.append(
        "- Repaired and simplified attempts must compile before they are treated as verified artifacts."
    )
    report.append(
        "- Hashes and line counts catch exact-file differences; structural features capture proof-strategy differences."
    )
    report.append(
        "- Semantic equivalence is approximated here by matching theorem type plus successful Lean verification."
    )
    report.append("")
    return "\n".join(report)


def main() -> None:
    lake = lake_command()
    rows = [compare_file(lake, model, stage, path) for model, stage, path in FILES]
    OUTPUT_PATH.write_text(build_report(rows), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
