param(
  [string]$OutputPath = "multi_model_workflow/comparison_report.md"
)

$ErrorActionPreference = "Continue"

$repoRoot = (Resolve-Path ".").Path
$wingetLake = Join-Path $env:LOCALAPPDATA "Microsoft\WinGet\Packages\Lean.Lean_Microsoft.Winget.Source_8wekyb3d8bbwe\lean-4.29.1-windows\bin\lake.exe"

if (Test-Path $wingetLake) {
  $lake = $wingetLake
} else {
  $lake = "lake"
}

$files = @(
  @{ Model = "Codex";  Stage = "Blind attempt";       Path = "generated_proofs/codex/agnostic_attempt_1.lean" },
  @{ Model = "Codex";  Stage = "Repaired attempt";    Path = "generated_proofs/codex/agnostic_attempt_2_repaired.lean" },
  @{ Model = "Codex";  Stage = "Simplified attempt";  Path = "generated_proofs/codex/simplified_attempt.lean" },
  @{ Model = "Claude"; Stage = "Blind attempt";       Path = "generated_proofs/claude/agnostic_attempt_1.lean" },
  @{ Model = "Claude"; Stage = "Repaired attempt";    Path = "generated_proofs/claude/agnostic_attempt_2_repaired.lean" },
  @{ Model = "Claude"; Stage = "Simplified attempt";  Path = "generated_proofs/claude/simplified_attempt.lean" }
)

function Get-FileSummary {
  param([string]$Path)

  $content = Get-Content $Path -Raw
  $codeOnly = ($content -split "`r?`n" | Where-Object {
    -not ($_.TrimStart().StartsWith("--")) -and
    -not ($_.TrimStart().StartsWith("/-")) -and
    -not ($_.TrimStart().StartsWith("-/"))
  }) -join "`n"
  $lines = ($content -split "`r?`n").Count
  $hash = (Get-FileHash $Path -Algorithm SHA256).Hash.Substring(0, 12)
  $usesCalc = $codeOnly.Contains("calc")
  $usesOmega = $codeOnly.Contains("omega")
  $usesAddRight = $codeOnly.Contains("Nat.add_le_add_right")
  $usesAssoc = $codeOnly.Contains("Nat.add_assoc")
  $callsMainTheorem = $codeOnly.Contains("agnostic_erm_deterministic P")
  $hasConjunctionExtraction = $codeOnly.Contains(".left") -or $codeOnly.Contains(".right")

  [PSCustomObject]@{
    Lines = $lines
    Hash = $hash
    UsesCalc = $usesCalc
    UsesOmega = $usesOmega
    UsesAddRight = $usesAddRight
    UsesAssoc = $usesAssoc
    CallsMainTheorem = $callsMainTheorem
    ExtractsConjunction = $hasConjunctionExtraction
  }
}

function Test-LeanFile {
  param([string]$Path)

  $output = & $lake env lean $Path 2>&1
  $exit = $LASTEXITCODE
  [PSCustomObject]@{
    ExitCode = $exit
    Compiles = ($exit -eq 0)
    Output = ($output | Out-String).Trim()
  }
}

$rows = @()

foreach ($entry in $files) {
  $path = $entry.Path
  $summary = Get-FileSummary $path
  $verification = Test-LeanFile $path
  $rows += [PSCustomObject]@{
    Model = $entry.Model
    Stage = $entry.Stage
    Path = $path
    Compiles = $verification.Compiles
    ExitCode = $verification.ExitCode
    Lines = $summary.Lines
    Hash = $summary.Hash
    UsesCalc = $summary.UsesCalc
    UsesOmega = $summary.UsesOmega
    UsesAddRight = $summary.UsesAddRight
    UsesAssoc = $summary.UsesAssoc
    CallsMainTheorem = $summary.CallsMainTheorem
    ExtractsConjunction = $summary.ExtractsConjunction
    Output = $verification.Output
  }
}

$report = New-Object System.Collections.Generic.List[string]
$report.Add("# Generated Proof Comparison Report")
$report.Add("")
$report.Add("Generated by `multi_model_workflow/run_comparison.ps1`.")
$report.Add("")
$report.Add("## Verification Summary")
$report.Add("")
$report.Add("| Model | Stage | File | Compiles? | Exit | Lines | SHA256 prefix |")
$report.Add("| --- | --- | --- | --- | --- | ---: | --- |")
foreach ($row in $rows) {
  $compiles = if ($row.Compiles) { "Yes" } else { "No" }
  $report.Add("| $($row.Model) | $($row.Stage) | ``$($row.Path)`` | $compiles | $($row.ExitCode) | $($row.Lines) | ``$($row.Hash)`` |")
}

$report.Add("")
$report.Add("## Structural Feature Comparison")
$report.Add("")
$report.Add("| Model | Stage | calc | omega | add_right | assoc | calls main theorem | extracts conjunction |")
$report.Add("| --- | --- | --- | --- | --- | --- | --- | --- |")
foreach ($row in $rows) {
  $report.Add("| $($row.Model) | $($row.Stage) | $($row.UsesCalc) | $($row.UsesOmega) | $($row.UsesAddRight) | $($row.UsesAssoc) | $($row.CallsMainTheorem) | $($row.ExtractsConjunction) |")
}

$report.Add("")
$report.Add("## Failure Outputs")
$report.Add("")
foreach ($row in $rows | Where-Object { -not $_.Compiles }) {
  $report.Add("### $($row.Model) - $($row.Stage)")
  $report.Add("")
  $report.Add('```text')
  if ([string]::IsNullOrWhiteSpace($row.Output)) {
    $report.Add("(no output)")
  } else {
    $report.Add($row.Output)
  }
  $report.Add('```')
  $report.Add("")
}

$report.Add("## Interpretation")
$report.Add("")
$report.Add("- Blind attempts are allowed to fail; their failures are the verifier feedback used for repair.")
$report.Add("- Repaired and simplified attempts must compile before they are treated as verified artifacts.")
$report.Add("- Hashes and line counts catch exact-file differences; structural features capture proof-strategy differences.")
$report.Add("- Semantic equivalence is approximated here by matching theorem type plus successful Lean verification.")

Set-Content -Path $OutputPath -Value $report -Encoding UTF8
Write-Host "Wrote $OutputPath"
